routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a given Closure or controller and enjoy the fresh air.
|
*/

/*
|--------------------------------------------------------------------------
| Welcome Page
|--------------------------------------------------------------------------
*/

Route::get('/', 'PagesController@home');

/*
|--------------------------------------------------------------------------
| Login/ Logout/ Password
|--------------------------------------------------------------------------
*/
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::get('logout', 'Auth\LoginController@logout')->name('logout');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

/*
|--------------------------------------------------------------------------
| Registration & Activation
|--------------------------------------------------------------------------
*/
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');

Route::get('activate/token/{token}', 'Auth\ActivateController@activate');
Route::group(['middleware' => ['auth']], function () {
    Route::get('activate', 'Auth\ActivateController@showActivate');
    Route::get('activate/send-token', 'Auth\ActivateController@sendToken');
});

/*
|--------------------------------------------------------------------------
| Authenticated Routes
|--------------------------------------------------------------------------
*/
Route::group(['middleware' => ['auth', 'active']], function () {

    /*
    |--------------------------------------------------------------------------
    | General
    |--------------------------------------------------------------------------
    */

    Route::get('/users/switch-back', 'Admin\UserController@switchUserBack');

    /*
    |--------------------------------------------------------------------------
    | User
    |--------------------------------------------------------------------------
    */

    Route::group(['prefix' => 'user', 'namespace' => 'User'], function () {
        Route::get('settings', 'SettingsController@settings');
        Route::post('settings', 'SettingsController@update');
        Route::get('password', 'PasswordController@password');
        Route::post('password', 'PasswordController@update');
    });

    /*
    |--------------------------------------------------------------------------
    | Dashboard
    |--------------------------------------------------------------------------
    */

    Route::get('/dashboard', 'PagesController@dashboard');
    Route::get('/generateData', 'PagesController@generateData');
    Route::get('/generateData2/{variable_id}/{lat}/{lng}', 'PagesController@generateData2');
    Route::get('/clearData', 'PagesController@clearData');
    Route::get('/filter', 'PagesController@filter');

    /*
    |--------------------------------------------------------------------------
    | Team Routes
    |--------------------------------------------------------------------------
    */

    Route::get('team/{name}', 'TeamController@showByName');
    Route::resource('teams', 'TeamController', ['except' => ['show']]);
    Route::post('teams/search', 'TeamController@search');
    Route::post('teams/{id}/invite', 'TeamController@inviteMember');
    Route::get('teams/{id}/remove/{userId}', 'TeamController@removeMember');

    /*
    |--------------------------------------------------------------------------
    | Admin
    |--------------------------------------------------------------------------
    */

    Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'admin'], function () {

        Route::get('dashboard', 'DashboardController@index');

        /*
        |--------------------------------------------------------------------------
        | Users
        |--------------------------------------------------------------------------
        */
        Route::resource('users', 'UserController', ['except' => ['create', 'show']]);
        Route::post('users/search', 'UserController@search');
        Route::get('users/search', 'UserController@index');
        Route::get('users/invite', 'UserController@getInvite');
        Route::get('users/switch/{id}', 'UserController@switchToUser');
        Route::post('users/invite', 'UserController@postInvite');

        /*
        |--------------------------------------------------------------------------
        | Roles
        |--------------------------------------------------------------------------
        */
        Route::resource('roles', 'RoleController', ['except' => ['show']]);
        Route::post('roles/search', 'RoleController@search');
        Route::get('roles/search', 'RoleController@index');
    });
});

/*
|--------------------------------------------------------------------------
| Variable Routes
|--------------------------------------------------------------------------
*/

Route::resource('variables', 'VariablesController', ['except' => ['show']]);
Route::post('variables/search', [
    'as' => 'variables.search',
    'uses' => 'VariablesController@search'
]);

/*
|--------------------------------------------------------------------------
| Opinion Routes
|--------------------------------------------------------------------------
*/

Route::resource('opinions', 'OpinionsController', ['except' => ['show']]);
Route::post('opinions/search', [
    'as' => 'opinions.search',
    'uses' => 'OpinionsController@search'
]);

Route::get('opinions/create2/{user_id}/{variable_id}', 'OpinionsController@create2');
Route::get('opinions/userindex', ['as' => 'opinions.userindex', 'uses' => 'OpinionsController@userindex']);

app/Models/Opinion.php
<?php

namespace App\Models;

use App\Models\User;
use App\Models\Variable;
use Illuminate\Database\Eloquent\Model;

class Opinion extends Model
{
    public $table = "opinions";

    public $primaryKey = "id";

    public $timestamps = true;

    public $fillable = [
		'id',
		'user_id',
		'variable_id',
		'value',
		'lat',
    'lng',
    'radius'
    ];

    public static $rules = [
        // create rules
    ];

	public function user() {
		return $this->belongsTo(User::class);
	}

	public function variable() {
		return $this->belongsTo(Variable::class);
	}

}

app/Http/Controllers/OpinionsController.php
<?php

namespace App\Http\Controllers;

use Auth;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Services\OpinionService;
use App\Http\Requests\OpinionCreateRequest;
use App\Http\Requests\OpinionUpdateRequest;

class OpinionsController extends Controller
{
    public function __construct(OpinionService $opinion_service)
    {
        $this->service = $opinion_service;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $opinions = $this->service->paginated();
        return view('opinions.index')->with('opinions', $opinions);
    }

    /**
     * Display a listing of the resource of an user
     *
     * @return \Illuminate\Http\Response
     */
    public function userindex(Request $request)
    {
        $user_id = Auth::user()->id;
        $opinions = $this->service->userindex($user_id);
        return view('opinions.userindex')->with('opinions', $opinions);
    }

    /**
     * Display a listing of the resource searched.
     *
     * @return \Illuminate\Http\Response
     */
    public function search(Request $request)
    {
        $opinions = $this->service->search($request->search);
        return view('opinions.index')->with('opinions', $opinions);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user_id = Auth::user()->id;
        return view('opinions.create', ['user_id' => $user_id]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\OpinionCreateRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(OpinionCreateRequest $request)
    {
        $result = $this->service->create($request->except('_token'));

        if ($result) {
            return redirect(route('opinions.edit', ['id' => $result->id]))->with('message', 'Successfully created');
        }

        return redirect(route('opinions.index'))->with('message', 'Failed to create');
    }

    /**
     * Display the opinion.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $opinion = $this->service->find($id);
        return view('opinions.show')->with('opinion', $opinion);
    }

    /**
     * Show the form for editing the opinion.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $opinion = $this->service->find($id);
        return view('opinions.edit')->with('opinion', $opinion);
    }

    /**
     * Update the opinions in storage.
     *
     * @param  \Illuminate\Http\OpinionUpdateRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(OpinionUpdateRequest $request, $id)
    {
        $result = $this->service->update($id, $request->except('_token'));

        if ($result) {
            return back()->with('message', 'Successfully updated');
        }

        return back()->with('message', 'Failed to update');
    }

    /**
     * Remove the opinions from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $result = $this->service->destroy($id);

        if ($result) {
            return redirect(route('opinions.index'))->with('message', 'Successfully deleted');
        }

        return redirect(route('opinions.index'))->with('message', 'Failed to delete');
    }
}

resources/views/opinions/create.blade.php
@extends('dashboard', ['pageTitle' => '_camelUpper_casePlural_ &raquo; Create'])

@section('content')

    <style>
       #map {
        height: 600px;
        width: 100%;
       }
    </style>

    <div class="row">
        <div class="col-md-12">
            <div class="pull-right raw-margin-top-24 raw-margin-left-24">
                {!! Form::open(['route' => 'opinions.search']) !!}
                <input class="form-control form-inline pull-right" name="search" placeholder="Search">
                {!! Form::close() !!}
            </div>
            <h1 class="pull-left">Opinions: Create</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">

            {!! Form::open(['route' => 'opinions.store']) !!}

            <div class="form-group col-sm-12">
              Variable: @input_maker_create('variable_id', ['type' => 'relationship', 'model' => '\App\Models\Variable'])
            </div>


            <div class="form-group col-sm-12">
              Value: @input_maker_create('value', ['type' => 'select', 'options' => range(0,10)])
            </div>

            <div class="form-group col-sm-12">
              Lat: @input_maker_create('lat', [ 'type' => 'string', 'default_value' => "global" ])
              Lng: @input_maker_create('lng', [ 'type' => 'string', 'default_value' => "global" ])
              Radius: @input_maker_create('radius', [ 'type' => 'select', 'default_value' => "3", 'options' => range(0,10) ])
              <br>
              <div id="map"></div>
            </div>

            @input_maker_create('user_id', [ 'type' => 'hidden', 'default_value' => $user_id ])

            {!! Form::submit('Save', ['class' => 'btn btn-primary pull-right']) !!}

            {!! Form::close() !!}

        </div>
    </div>

    <script>
      var marker;
      var map;
      var circle;



      function initMap() {
        var main_location = {lat: 28.127222, lng: -15.431389};
        map = new google.maps.Map(document.getElementById('map'), {
          zoom: 16,
          center: main_location,
          navigationControl: false
        });
        marker = new google.maps.Marker({
          position: main_location,
          map: map
        });

        var radius = $('#Radius').val();
        circle = new google.maps.Circle({
          strokeColor: '#FF0000',
          strokeOpacity: 0.8,
          strokeWeight: 2,
          fillColor: '#FF0000',
          fillOpacity: 0.35,
          map: map,
          center: main_location,
          radius: radius * 100
        });

        google.maps.event.addListener(map, 'click', function(event) {
            placeMarker(event.latLng);
        });

        google.maps.event.addDomListener(
           document.getElementById('Radius'), 'change', function() {
             var radius = $('#Radius').val();
             circle.setRadius(radius*25);
           });

      }

      function placeMarker(location) {
          if (marker == undefined){
              marker = new google.maps.Marker({
                  position: location,
                  map: map,
                  animation: google.maps.Animation.DROP,
              });
          }
          else{
              marker.setPosition(location);
          }
          map.setCenter(location);
          circle.setCenter(location);

          $('input[name="lat"]').val(location.lat);
          $('input[name="lng"]').val(location.lng);
      }

    </script>

    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyApGSINLZK7CbaOtuH4toxMPfUMbsH2QMs&callback=initMap">
    </script>

@stop

resources/views/opinions/create2.blade.php
@extends('dashboard', ['pageTitle' => '_camelUpper_casePlural_ &raquo; Create'])

@section('content')

    <style>
       #map {
        height: 600px;
        width: 100%;
       }
    </style>

    <div class="row">
        <div class="col-md-12">
            <div class="pull-right raw-margin-top-24 raw-margin-left-24">
                {!! Form::open(['route' => 'opinions.search']) !!}
                <input class="form-control form-inline pull-right" name="search" placeholder="Search">
                {!! Form::close() !!}
            </div>
            <h1 class="pull-left">Opinions: Create</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">

            {!! Form::open(['route' => 'opinions.store']) !!}

            {{-- @form_maker_table("opinions") --}}

            <h2>{{ $variable->name }}</h2>

            <div class="form-group col-sm-12">
              Value: @input_maker_create('value', ['type' => $type, 'options' => $options])
            </div>

            <div class="form-group col-sm-12">
              Lat: @input_maker_create('lat', [ 'type' => 'string', 'default_value' => "global" ])
              Lng: @input_maker_create('lng', [ 'type' => 'string', 'default_value' => "global" ])
              Radius: @input_maker_create('radius', [ 'type' => 'select', 'default_value' => "3", 'options' => $radius ])
              <br>
              <div id="map"></div>
            </div>

            @input_maker_create('variable_id', [ 'type' => 'hidden', 'default_value' => "$variable_id" ])

            @input_maker_create('user_id', [ 'type' => 'hidden', 'default_value' => $user_id ])

            {!! Form::submit('Save', ['class' => 'btn btn-primary pull-right']) !!}

            {!! Form::close() !!}

        </div>
    </div>

    <script>
      var marker;
      var map;
      var circle;

      $(document).ready(function() {

      });


      function initMap() {
        var main_location = {lat: 28.127222, lng: -15.431389};
        map = new google.maps.Map(document.getElementById('map'), {
          zoom: 16,
          center: main_location,
          navigationControl: false
        });
        marker = new google.maps.Marker({
          position: main_location,
          map: map
        });

        var radius = $('#Radius').val();
        circle = new google.maps.Circle({
          strokeColor: '#FF0000',
          strokeOpacity: 0.8,
          strokeWeight: 2,
          fillColor: '#FF0000',
          fillOpacity: 0.35,
          map: map,
          center: main_location,
          radius: radius * 100
        });

        google.maps.event.addListener(map, 'click', function(event) {
            placeMarker(event.latLng);
        });

        google.maps.event.addDomListener(
           document.getElementById('Radius'), 'change', function() {
             var radius = $('#Radius').val();
             circle.setRadius(radius*25);
           });

      }

      function placeMarker(location) {
          if (marker == undefined){
              marker = new google.maps.Marker({
                  position: location,
                  map: map,
                  animation: google.maps.Animation.DROP,
              });
          }
          else{
              marker.setPosition(location);
          }
          map.setCenter(location);
          circle.setCenter(location);

          $('input[name="lat"]').val(location.lat);
          $('input[name="lng"]').val(location.lng);

      }

    </script>

    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyApGSINLZK7CbaOtuH4toxMPfUMbsH2QMs&callback=initMap">
    </script>

@stop

resources/views/opinions/edit.blade.php
@extends('dashboard', ['pageTitle' => '_camelUpper_casePlural_ &raquo; Edit'])

@section('content')

<style>
   #map {
    height: 600px;
    width: 100%;
   }
</style>


    <div class="row">
        <div class="col-md-12">
            <div class="pull-right raw-margin-top-24 raw-margin-left-24">
                {!! Form::open(['route' => 'opinions.search']) !!}
                <input class="form-control form-inline pull-right" name="search" placeholder="Search">
                {!! Form::close() !!}
            </div>
            <h1 class="pull-left">Opinions: Edit</h1>
            <a class="btn btn-primary pull-right raw-margin-top-24 raw-margin-right-8" href="{!! route('opinions.create') !!}">Add New</a>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">

            {!! Form::model($opinion, ['route' => ['opinions.update', $opinion->id], 'method' => 'patch']) !!}


            <div class="form-group col-sm-12">
              Variable: {{ $opinion->variable->name }}
            </div>


            <div class="form-group col-sm-12">
              Value: @input_maker_create('value', ['type' => 'select', 'options' => range(0,10), 'default_value' => $opinion->value])
            </div>

            <div class="form-group col-sm-12">
              Lat: @input_maker_create('lat', [ 'type' => 'string', 'default_value' => $opinion->lat ])
              Lng: @input_maker_create('lng', [ 'type' => 'string', 'default_value' => $opinion->lng ])
              Radius: @input_maker_create('radius', [ 'type' => 'select', 'default_value' => $opinion->radius, 'options' => range(0,10) ])
              <br>
              <div id="map"></div>
            </div>

            @input_maker_create('user_id', [ 'type' => 'hidden', 'default_value' => $opinion->user_id ])

            {!! Form::submit('Update', ['class' => 'btn btn-primary pull-right']) !!}

            {!! Form::close() !!}

        </div>
    </div>

    <script>
      var marker;
      var map;
      var circle;

      function initMap() {
        var main_location = {lat: {{$opinion->lat}}, lng: {{$opinion->lng}}};

        map = new google.maps.Map(document.getElementById('map'), {
          zoom: 16,
          center: main_location,
          navigationControl: false
        });
        placeMarker(main_location);

        google.maps.event.addListener(map, 'click', function(event) {
            placeMarker(event.latLng);
        });

        google.maps.event.addDomListener(
           document.getElementById('Radius'), 'change', function() {
             var radius = $('#Radius').val();
             circle.setRadius(radius*25);
           });

      }

      function placeMarker(location) {
          if (marker == undefined){
              marker = new google.maps.Marker({
                  position: location,
                  map: map,
                  animation: google.maps.Animation.DROP,
              });
          }
          else{
              marker.setPosition(location);
          }
          if(circle == undefined) {

            circle = new google.maps.Circle({
              strokeColor: '#FF0000',
              strokeOpacity: 0.8,
              strokeWeight: 2,
              fillColor: '#FF0000',
              fillOpacity: 0.35,
              map: map,
              center: location,
              radius: {{$opinion->radius}} * 25
            });
          } else {
            circle.setCenter(location);
          }
          map.setCenter(location);

          $('input[name="lat"]').val(location.lat);
          $('input[name="lng"]').val(location.lng);
      }

    </script>

    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyApGSINLZK7CbaOtuH4toxMPfUMbsH2QMs&callback=initMap">
    </script>


@stop

resources/views/opinions/fields.blade.php
<div class="form-group col-sm-12">
  @input_maker_create('value', [ 'type' => 'string' ])
</div>

<div class="form-group col-sm-12">
@input_maker_create('variable_id', [ 'type' => 'relationship', 'model' => 'App\Models\Variable' ])
</div>

<div class="form-group col-sm-12">
@input_maker_create('user_id', [ 'type' => 'relationship', 'model' => 'App\Models\User' ])
</div>

resources/views/opinions/fields2.blade.php
<div class="form-group col-sm-12">
  @input_maker_create('value', ['type' => '@type', 'options' => [1=>1, 2=>2]])
</div>

@input_maker_create('variable_id', [ 'type' => 'hidden', 'value' => '@variable_id' ])

@input_maker_create('user_id', [ 'type' => 'hidden', 'value' => '@user_id' ])

resources/views/opinions/index.blade.php
@extends('dashboard', ['pageTitle' => '_camelUpper_casePlural_ &raquo; Index'])

@section('content')

    <div class="row">
        <div class="col-md-12">
            <div class="pull-right raw-margin-top-24 raw-margin-left-24">
                {!! Form::open(['route' => 'opinions.search']) !!}
                <input class="form-control form-inline pull-right" name="search" placeholder="Search">
                {!! Form::close() !!}
            </div>
            <h1 class="pull-left">Opinions</h1>
            <a class="btn btn-primary pull-right raw-margin-top-24 raw-margin-right-8" href="{!! route('opinions.new') !!}">Add New</a>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            @if ($opinions->isEmpty())
                <div class="well text-center">No opinions found.</div>
            @else
                <table class="table table-striped">
                    <thead>
                        <th>Name</th>
                        <th>Value</th>
                        <th class="text-right" width="200px">Action</th>
                    </thead>
                    <tbody>
                        @foreach($opinions as $opinion)
                            <tr>
                                <td>
                                    <a href="{!! route('opinions.edit', [$opinion->id]) !!}">{{ $opinion->variable->name }}</a>
                                </td>
                                <td>
                                    <a href="{!! route('opinions.edit', [$opinion->id]) !!}">{{ $opinion->value }}</a>
                                </td>
                                <td class="text-right">
                                    <form method="post" action="{!! route('opinions.destroy', [$opinion->id]) !!}">
                                        {!! csrf_field() !!}
                                        {!! method_field('DELETE') !!}
                                        <button class="btn btn-danger btn-xs pull-right" type="submit" onclick="return confirm('Are you sure you want to delete this opinion?')"><i class="fa fa-trash"></i> Delete</button>
                                    </form>
                                    <a class="btn btn-default btn-xs pull-right raw-margin-right-16" href="{!! route('opinions.edit', [$opinion->id]) !!}"><i class="fa fa-pencil"></i> Edit</a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            @endif
        </div>
    </div>

    <div class="row">
        <div class="col-md-12 text-center">
            {!! $opinions; !!}
        </div>
    </div>

@stop

resources/views/opinions/show.blade.php
@extends('dashboard', ['pageTitle' => '_camelUpper_casePlural_ &raquo; Show'])

@section('content')

    <div class="container">
        <div class="col-md-12">

        <!-- Put fields here -->

        </div>
    </div>

@stop

resources/views/opinions/userindex.blade.php
@extends('dashboard', ['pageTitle' => '_camelUpper_casePlural_ &raquo; Index'])

@section('content')

    <div class="row">
        <div class="col-md-12">
            <div class="pull-right raw-margin-top-24 raw-margin-left-24">
                {!! Form::open(['route' => 'opinions.search']) !!}
                <input class="form-control form-inline pull-right" name="search" placeholder="Search">
                {!! Form::close() !!}
            </div>
            <h1 class="pull-left">My opinions</h1>
            <a class="btn btn-primary pull-right raw-margin-top-24 raw-margin-right-8" href="{!! route('opinions.create') !!}">Add New</a>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            @if ($opinions->isEmpty())
                <div class="well text-center">No opinions found.</div>
            @else
                <table class="table table-striped">
                  <thead>
                      <th>Name</th>
                      <th>Value</th>
                      <th>Creation date</th>
                      <th>Updated date</th>
                      <th class="text-right" width="200px">Action</th>
                  </thead>
                  <tbody>
                      @foreach($opinions as $opinion)
                          <tr>
                              <td>
                                  <a href="{!! route('opinions.edit', [$opinion->id]) !!}">{{ $opinion->variable->name }}</a>
                              </td>
                              <td>
                                  <a href="{!! route('opinions.edit', [$opinion->id]) !!}">{{ $opinion->value }}</a>
                              </td>
                              <td>
                                  <a href="{!! route('opinions.edit', [$opinion->id]) !!}">{{ $opinion->created_at }}</a>
                              </td>
                              <td>
                                  <a href="{!! route('opinions.edit', [$opinion->id]) !!}">{{ $opinion->updated_at }}</a>
                              </td>
                                <td class="text-right">
                                    <form method="post" action="{!! route('opinions.destroy', [$opinion->id]) !!}">
                                        {!! csrf_field() !!}
                                        {!! method_field('DELETE') !!}
                                        <button class="btn btn-danger btn-xs pull-right" type="submit" onclick="return confirm('Are you sure you want to delete this opinion?')"><i class="fa fa-trash"></i> Delete</button>
                                    </form>
                                    <a class="btn btn-default btn-xs pull-right raw-margin-right-16" href="{!! route('opinions.edit', [$opinion->id]) !!}"><i class="fa fa-pencil"></i> Edit</a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            @endif
        </div>
    </div>

    <div class="row">
        <div class="col-md-12 text-center">
            {!! $opinions; !!}
        </div>
    </div>

@stop